# Generated by Django 5.0.6 on 2024-08-05 21:03

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0003_rename_wishlist_wishlist_model_alter_category_cid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('message', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='cid',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='pid',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vid',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=30, unique=True),
        ),
    ]
